_target_: diffusion_policy.workspace.train_autoregressive_workspace.TrainAutoregressiveWorkspace
train_stage: second_stage_unipi_pixel
task_name: pusht_image
# name: train_diffusion_unipi_pixel
# dataset_obs_steps: 2
# exp_name: default
# horizon: 16
# keypoint_visible_rate: 1.0
# n_action_steps: 8
# n_latency_steps: 0
# n_obs_steps: 2
# obs_as_cond: true
# past_action_visible: false

task:
  name: pusht_image
  
  dataset:
    _target_: diffusion_policy.dataset.pusht_image_dataset.PushTImageDataset
    horizon: 32
    max_train_episodes: 90
    pad_after: 7
    pad_before: 1
    seed: 42
    val_ratio: 0.02
    zarr_path: /local/real/shuang/data/diffusion_policy/pusht/pusht_cchi_v7_replay.zarr
    language_emb_model: null


  env_runner:
    _target_: diffusion_policy.env_runner.pusht_image_runner.PushTImageRunner
    fps: 10
    legacy_test: true
    max_steps: 300
    n_action_steps: 8
    n_envs: null
    n_obs_steps: 16
    n_test: 20
    n_test_vis: 4
    n_train: 6
    n_train_vis: 2
    past_action: false
    test_start_seed: 100000
    train_start_seed: 0
    fix_goal: true

dataloader:
  # batch_size: 96
  batch_size: 64
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: true

val_dataloader:
  # batch_size: 96
  batch_size: 64
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: false

training:
  checkpoint_every: 10
  debug: false
  device: cuda:0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 1000
  max_train_steps: null
  max_val_steps: null
  num_epochs: 3050
  # num_epochs: 6100
  resume: true
  rollout_every: 10
  sample_every: 5
  seed: 42
  tqdm_interval_sec: 1.0
  use_ema: true
  val_every: 1
  mixed_precision: 'no'

  
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt
    k: 5
    mode: max
    monitor_key: test_mean_score


ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0

logging:
  group: null
  id: null
  mode: online
  name: train_diffusion_my_transformer_pusht_image
  project: diffusion_policy_v1
  resume: true
  tags:
  - train_diffusion_my_transformer
  - pusht_image
  - default

multi_run:
  run_dir: data/outputs/train_diffusion_unipi_pixel_pusht_image
  wandb_name_base: train_diffusion_my_unipi_pixel_pusht_image

first_stage_model:
  _target_: diffusion_policy.policy.first_stage_model.FirstStageModel
  autoencoder_path: none
  ddconfig:
    embed_dim: 4
    double_z: False
    channels: 384
    timesteps: 16
    skip: 1
    in_channels: 3
    out_ch: 3
    num_res_blocks: 2
    attn_resolutions: []
    splits: 1
    autoencoder_project_pos_ebm: fix
    time_downsample: 4
    patch_size: 8
    select_timesteps: -1
    lossconfig_disc_start: 100000000
  optimizer:
    betas:
    - 0.5
    - 0.9
    learning_rate: 0.0001
    
policy:
  _target_: diffusion_policy.policy.diffusion_unipi_image_policy.DiffusionUnipiImagePolicy
  debug: None
  horizon: 8
  n_action_steps: 8
  n_obs_steps: 16
  obs_as_cond: true
  # causal_attn: true
  # crop_shape:
  # - 84
  # - 84
  # eval_fixed_crop: true
  # n_cond_layers: 0
  # n_emb: 256
  # n_head: 4
  # n_layer: 8
  # num_inference_steps: 100
  # obs_encoder_group_norm: true
  # p_drop_attn: 0.3
  # p_drop_emb: 0.0
  # time_as_cond: true

  video_diffusion_params:
    pretrained_diffusion_model_path: /store/real/shuang/PVDM/results/PushT/ddpm_main_PushT_42_transformer_fix_original_DiT_S_2_im96_AEtimesample4_AEpatch8/ema_model_50000.pth
    custom_cond: original
    cond_prob: 0.3
    diffusion_model_type: base_unipi_pixel

    model_config:
      # image_size doesn't matter, it is not used in the model
      image_size: [96, 96]
      in_channels: 3
      model_channels: 128
      out_channels: 3
      num_res_blocks: 2
      attention_resolutions: [8, 16]
      dropout: 0
      channel_mult: [1, 2, 3, 4, 5]
      conv_resample: True
      dims: 3
      # num_classes: None
      # task_tokens: True
      task_token_channels: 512
      use_checkpoint: False
      use_fp16: False
      num_head_channels: 32
      language_emb_model: null
  action_model_params:
    action_input_type: subtract_noise
    predict_action: True
    pretrained_action_model_path: /store/real/shuang/PVDM/results/action_prediction_main_PushT_42_unipi_pixel_action_prediction/model_4000.pth

  ddpm_solver: ddpm_avdc
  shift_action: True

  optimizer:
    optimize_type: both_decay3
    betas:
    - 0.9
    - 0.95
    learning_rate: 0.0001
    obs_encoder_weight_decay: 1.0e-06
    transformer_weight_decay: 0.001
  
  ddpm_diffusers_config:
    num_train_timesteps: 100
    beta_start: 0.0001
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    variance_type: fixed_small # Yilun's paper uses fixed_small_log instead, but easy to cause Nan
    clip_sample: True # required when predict_epsilon=False
    prediction_type: epsilon # or sample
    loss_type: l2

  ddpm_avdc_config:
    timesteps: 100
    sampling_timesteps: 100 ## this number is only used for inference, training doesn't use this sampling_timesteps, training use default=1000
    loss_type: l2
    parameterization: v
    beta_schedule: cosine
    min_snr_loss_weight: True
    # variance_type: fixed_small
    variance_type: fixed_small_log

  ddpm_ori_config:  
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    sampling_timesteps: 10 ## this number is only used for inference, training doesn't use this sampling_timesteps, training use default=1000
    loss_type: l2
    first_stage_key: "image"
    cond_stage_key: "image"
    image_size: 32
    channels: 4
    cond_stage_trainable: False
    concat_mode: False
    scale_by_std: True
    w: 0.
    parameterization: "eps"
    # parameterization: "x0"
    # parameterization: "v"
    beta_schedule: linear
    auto_normalize: False

    # scheduler_config: # 10000 warmup steps
    #   warm_up_steps: [10000]
    #   cycle_lengths: [10000000000000]
    #   f_start: [1.e-6]
    #   f_max: [1.]
    #   f_min: [ 1.]

shape_meta:
  image_resolution: 96
  action:
    shape:
    - 2
  obs:
    agent_pos:
      shape:
      - 2
      type: low_dim
    image:
      shape:
      - 3
      - 96
      - 96
      type: rgb
