name: diffusion_policy

dataset_obs_steps: 2
exp_name: default
horizon: 10
keypoint_visible_rate: 1.0
n_action_steps: 8
n_latency_steps: 0
n_obs_steps: 2
obs_as_cond: true
past_action_visible: false
task_name: libero_10_image

shape_meta: &shape_meta
  action:
    shape:
    - 10
  obs:
    agentview_rgb:
      shape:
      - 3
      - 128
      - 128
      type: rgb
    language:
      shape:
      - 15

shape_meta_env: &shape_meta_env
  action:
    shape:
    - 10
  obs:
    agentview_image:
      shape:
      - 3
      - 128
      - 128
      type: rgb
    
task:
  abs_action: true
  dataset:
    _target_: unified_video_action.dataset.libero_replay_image_dataset.LiberoReplayImageDataset
    abs_action: true
    dataset_path: data/libero_10
    language_emb_model: clip
    horizon: 10
    n_obs_steps: 2
    pad_after: 7
    pad_before: 1
    rotation_rep: rotation_6d
    seed: 42
    shape_meta: *shape_meta
    use_cache: true
    val_ratio: 0.02
  dataset_type: mh
  
  env_runner:
    _target_: unified_video_action.env_runner.libero_image_runner.LiberoImageRunner
    abs_action: true
    crf: 22
    dataset_path: data/libero_10
    fps: 10
    max_steps: 500
    n_action_steps: 8
    n_envs: null
    n_obs_steps: 2
    n_test: 3
    n_test_vis: 1
    n_train: 1
    n_train_vis: 1
    past_action: false
    render_obs_key: agentview_image
    shape_meta: *shape_meta_env
    test_start_seed: 100000
    tqdm_interval_sec: 1.0
    train_start_idx: 0
  
  name: libero_10_image
  shape_meta: *shape_meta
  task_name: libero_10

model:
  _target_: unified_video_action.workspace.train_diffusion_transformer_hybrid_workspace.TrainDiffusionTransformerHybridWorkspace

  policy:
    _target_: unified_video_action.policy.diffusion_transformer_hybrid_image_policy.DiffusionTransformerHybridImagePolicy
    debug: None
    causal_attn: true
    crop_shape:
    - 84
    - 84
    eval_fixed_crop: true
    horizon: 10
    n_action_steps: 8
    n_cond_layers: 0
    n_emb: 256
    n_head: 4
    n_layer: 8
    n_obs_steps: 2
    noise_scheduler:
      _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
      beta_end: 0.02
      beta_schedule: squaredcos_cap_v2
      beta_start: 0.0001
      clip_sample: true
      num_train_timesteps: 100
      prediction_type: epsilon
      variance_type: fixed_small
    num_inference_steps: 100
    obs_as_cond: true
    obs_encoder_group_norm: true
    p_drop_attn: 0.3
    p_drop_emb: 0.0
    shape_meta: *shape_meta
    time_as_cond: true

optimizer:
  betas:
  - 0.9
  - 0.95
  learning_rate: 0.0001
  obs_encoder_weight_decay: 1.0e-06
  transformer_weight_decay: 0.001

dataloader:
  batch_size: 64
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: true

val_dataloader:
  batch_size: 64
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: false

training:
  checkpoint_every: 10
  debug: false
  device: cuda:0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 1000
  max_train_steps: null
  max_val_steps: null
  num_epochs: 3500
  resume: true
  rollout_every: 10
  sample_every: 5
  seed: 42
  tqdm_interval_sec: 1.0
  use_ema: true
  val_every: 1
  mixed_precision: 'fp16'

checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt
    k: 1
    mode: max
    monitor_key: test_mean_score

ema:
  _target_: unified_video_action.model.diffusion.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0

logging:
  group: null
  id: null
  mode: online
  name: 2023.01.04-04.00.42_train_diffusion_transformer_hybrid_libero_10_image
  project: diffusion_policy_debug
  resume: true
  tags:
  - train_diffusion_transformer_hybrid
  - libero_10_image
  - default

multi_run:
  run_dir: data/outputs/2023.01.04/04.00.42_train_diffusion_transformer_hybrid_libero_10_image
  wandb_name_base: 2023.01.04-04.00.42_train_diffusion_transformer_hybrid_libero_10_image